version: '3.8'

services:
  postgres:
    container_name: to_do_list
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=to-do-list_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: